### ISSUE TITLE
User stories

### ISSUE THREAD

**Issue by JohannMoller** [lowdefy/lowdefy-example-crm#2]
### Users

- Agents
- Managers
- Admin

##### Create

1. Add company

   - Add attributes and labels

2. Add existing contact to company when creating company

   - Show warning if contact belongs to another company
   - Remove contact from previous company

3. Add new contact to company when creating company

   ##### View

4. View list of all companies

5. View list of companies that I've captured

6. View list of  companies filtered by label

7. Search for a specific company

   - Search for specific company filtered by label

8. View company attributes

9. View total deals value at various stage categories

10. View all contacts in company

11. Click through to view contact details

12. View all company deals

    - Deal value
    - Stage category
    - Expected close date

13. Click through to view deals details

14. View most recent interactions with company

15. Click through to view interaction details

16. Click through to view/search/filter list of all interactions with company

17. View archived companies and company details

    ##### Edit/Add

18. Add new contacts to any company

19. Add existing contacts to any company

    - Show warning if contact belongs to another company
    - Remove contact from previous company

20. Edit attributes/labels of any company

21. Archive company

22. Create new deal on any company captured

23. Create new interaction on any company

##### Create

1. Add contact

   - Add attributes and labels

2. Add existing company to contact when creating contact

3. Add new company to contact when creating contact

   ##### View

4. View list of all contacts

5. View list of all contacts in a specific company

6. View list of contacts that I've captured

7. View list of  contacts filtered by label

8. Search for a specific contact

   - Search for specific contact filtered by label/company

9. View contact attributes

10. View company contact belongs to

11. Click through to view company details

12. View all deals the contact is involved with

    - Deal value
    - Stage category
    - Expected

13. Click through to view deals details

14. View most recent interactions with contact

15. Click through to view interaction details

16. Click through to view/search/filter list of all interactions with contact

17. View archived contacts and contact details

    ##### Edit/Add

18. Change company contact belongs to

    - New
    - Existing

19. Edit attributes/labels of any contact

20. Archive contact

### Deals

1. Create new deal (with existing company/contact)

2. Create a deal (with new company and contact)

3. Add Contacts and companies to deal

4. View deal attributes

5. Move deal around in sales pipeline

6. Edit deal attributes

### Interactions

**Comment by JohannMoller** [comment]
Attributes data structure

```yaml
attributes:
  - min_stage: stage_4 // Deals
    name: nda_signed
    title: NDA Signed
    required: false
    required_progress: true // Deals
    validate: []
    validate_progress: // Deals
    type: TextInput/NumberInput/Switch/DateSelector/Selector/...
    properties:
      options:
      placeholder:
      Icons:
      ...
```
